import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/dashboard/app-sidebar"
import { DashboardBar } from "@/components/dashboard/dashboard-bar"
import { Poppins } from "next/font/google";
import { Metadata } from "next";
import './user.css'

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "E-Belanja Admin",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html>
        <body className={`${poppins.className} antialiased bg-[#EFF3FA]`}>
          <SidebarProvider>
            <div className="flex min-h-screen w-full">
              <AppSidebar />
              <div className="flex flex-1 flex-col">
                <DashboardBar />
                <main className="flex-1 p-4">{children}</main>
              </div>
            </div>
          </SidebarProvider>
          {children}
        </body>
      </html>
    </>
  )
}
