import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./user.css"
import "flickity/css/flickity.css"
import UserNavbar from "./components/UserNavbar";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[#EFF3FA]`}
      >
        <UserNavbar/> 
        {children}
      </body>
    </html>
  );
}
